### ISSUE TITLE
Getting error in console 

### ISSUE THREAD

**Issue by jamsheer-citrus** [Stratio/stratio-cassandra#22]
Some time i am getting error in server console and server goes shut down

ERROR [SharedPool-Worker-25] 2015-04-21 09:25:29,230 Log.java:49 - Error while indexing row 333032
WARN  [SharedPool-Worker-25] 2015-04-21 09:25:29,231 AbstractTracingAwareExecutorService.java:169 - Uncaught exception on thread Thread[SharedPool-Worker-25,5,main]: {}
java.lang.NullPointerException: null
	at com.stratio.cassandra.index.service.RowServiceWide.indexInner(RowServiceWide.java:82) ~[main/:na]
	at com.stratio.cassandra.index.service.RowService.index(RowService.java:139) ~[main/:na]
	at com.stratio.cassandra.index.RowIndex.index(RowIndex.java:154) ~[main/:na]
	at org.apache.cassandra.db.index.SecondaryIndexManager$StandardUpdater.updateRowLevelIndexes(SecondaryIndexManager.java:829) ~[main/:na]
	at org.apache.cassandra.db.AtomicBTreeColumns.addAllWithSizeDelta(AtomicBTreeColumns.java:229) ~[main/:na]
	at org.apache.cassandra.db.Memtable.put(Memtable.java:208) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1180) ~[main/:na]
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:385) ~[main/:na]
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:348) ~[main/:na]
	at org.apache.cassandra.db.commitlog.CommitLogReplayer$1.runMayThrow(CommitLogReplayer.java:419) ~[main/:na]
	at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0]
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[main/:na]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [main/:na]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0]
ERROR [SharedPool-Worker-26] 2015-04-21 09:25:29,341 Log.java:49 - Error while indexing row 333032
WARN  [SharedPool-Worker-26] 2015-04-21 09:25:29,381 AbstractTracingAwareExecutorService.java:169 - Uncaught exception on thread Thread[SharedPool-Worker-26,5,main]: {}
java.lang.NullPointerException: null
	at com.stratio.cassandra.index.service.RowServiceWide.indexInner(RowServiceWide.java:82) ~[main/:na]
	at com.stratio.cassandra.index.service.RowService.index(RowService.java:139) ~[main/:na]
	at com.stratio.cassandra.index.RowIndex.index(RowIndex.java:154) ~[main/:na]
	at org.apache.cassandra.db.index.SecondaryIndexManager$StandardUpdater.updateRowLevelIndexes(SecondaryIndexManager.java:829) ~[main/:na]
	at org.apache.cassandra.db.AtomicBTreeColumns.addAllWithSizeDelta(AtomicBTreeColumns.java:229) ~[main/:na]
	at org.apache.cassandra.db.Memtable.put(Memtable.java:208) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1180) ~[main/:na]
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:385) ~[main/:na]
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:348) ~[main/:na]
	at org.apache.cassandra.db.commitlog.CommitLogReplayer$1.runMayThrow(CommitLogReplayer.java:419) ~[main/:na]
	at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0]
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[main/:na]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [main/:na]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0]
INFO  [main] 2015-04-21 09:25:29,558 CommitLogReplayer.java:442 - Finished reading E:\softwares\DB\stratio\2.1.4\stratio-cassandra-master\stratio-cassandra-master\data\commitlog\CommitLog-4-1429501012554.log
ERROR [main] 2015-04-21 09:25:29,561 CassandraDaemon.java:550 - Exception encountered during startup
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:402) ~[main/:na]
	at org.apache.cassandra.utils.FBUtilities.waitOnFutures(FBUtilities.java:391) ~[main/:na]
	at org.apache.cassandra.db.commitlog.CommitLogReplayer.recover(CommitLogReplayer.java:427) ~[main/:na]
	at org.apache.cassandra.db.commitlog.CommitLogReplayer.recover(CommitLogReplayer.java:95) ~[main/:na]
	at org.apache.cassandra.db.commitlog.CommitLog.recover(CommitLog.java:148) ~[main/:na]
	at org.apache.cassandra.db.commitlog.CommitLog.recover(CommitLog.java:128) ~[main/:na]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:352) [main/:na]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:533) [main/:na]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:622) [main/:na]
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.get(AbstractTracingAwareExecutorService.java:200) ~[main/:na]
	at org.apache.cassandra.utils.FBUtilities.waitOnFuture(FBUtilities.java:398) ~[main/:na]
	... 8 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.stratio.cassandra.index.service.RowServiceWide.indexInner(RowServiceWide.java:82) ~[main/:na]
	at com.stratio.cassandra.index.service.RowService.index(RowService.java:139) ~[main/:na]
	at com.stratio.cassandra.index.RowIndex.index(RowIndex.java:154) ~[main/:na]
	at org.apache.cassandra.db.index.SecondaryIndexManager$StandardUpdater.updateRowLevelIndexes(SecondaryIndexManager.java:829) ~[main/:na]
	at org.apache.cassandra.db.AtomicBTreeColumns.addAllWithSizeDelta(AtomicBTreeColumns.java:229) ~[main/:na]
	at org.apache.cassandra.db.Memtable.put(Memtable.java:208) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore.apply(ColumnFamilyStore.java:1180) ~[main/:na]
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:385) ~[main/:na]
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:348) ~[main/:na]
	at org.apache.cassandra.db.commitlog.CommitLogReplayer$1.runMayThrow(CommitLogReplayer.java:419) ~[main/:na]
	at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0]
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[main/:na]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) ~[main/:na]
	at java.lang.Thread.run(Thread.java:722) ~[na:1.7.0]

What is the issue ?

**Comment by adelapena** [comment]
I will need a little more information to help you. Which version of Stratio Cassandra are you using? How is your schema? Which kind of operations are you doing when the exception is raised? Are you deleting rows or columns? Could you try to reproduce the issue with DEBUG log level and the index option 'indexing_threads' set to '0'? Thanks

**Comment by jamsheer-citrus** [comment]
Issue was with my indexing ,thanks
